### PR TITLE
add demo page

### LINKED ISSUE #3: demo page
Hi,

I just published a demo page on my fork and wanted to open a PR. But I think that because you don't have the `gh-pages` branch it isn't accepted. The demo is http://fpereira1.github.io/sbd/ - is that something you'd like to see merged?

### PR DESCRIPTION
**Pull request by fpereira1**
The branch will need to be merged into master then a new branch for gh-pages created from there. let me if clear (fixes #3)

### CODE REVIEW

**Comment by Tessmore** [comment]
Ye it's now merged in my own gh-pages branch. You can see it at http://tessmore.github.io/sbd/ 

Thanks!

**Comment by fpereira1** [comment]
@Tessmore You'll see the Makefile has a build step for building the sbd.js to run on the browser.

**Comment by fpereira1** [comment]
And you could add the URL to demo site so it's easier for people to test it out.  usually the website/demo goes in the project settings.

image

That's an example:

image

**Comment by Tessmore** [comment]
Hi @fpereira1, good suggestion. I added the link in the description.

**Pull request merged**
